### PR TITLE
PR title

### PR DESCRIPTION
**Pull request by andybons**
**Markdown description of PR**

### CODE REVIEW

**Comment by andybons** [comment]
Commenting on PR

**Comment by kevinburke** [comment]
This is happening, I guess...

**Comment by andybons** [comment]
Slowly

**Comment by andybons** [comment]
Bleh bleh bleh

<details>
<summary>Metadata for GerritBot</summary>
<pre>
Change-Id: I067803cf1f3d9f11eef6d8860232692d97c70099
Change-Num: 71850
</pre>
</details>

**Comment by andybons** [comment]
Updating change id

<details>
<summary>Metadata for GerritBot</summary>
  <pre>Change-Id: I18b62e3fd5515b9781cb2223bc071584288f517a</pre>
</details>

**Review by andybons — COMMENTED** [review]
How is this presented?

**Comment by andybons** [comment]
Comment to trigger GoogleBot CLA

**Comment by andybons** [comment]
Head fdac587adb53007dfe95f938047face239d899d1 has 2 commits. Please squash your commits into one.

**Comment by andybons** [comment]
PR (head at ce3ffdd40dbdf9bd3c7448b21f19cf04dca4eb4f) has been imported to Gerrit.

Please visit https://go-review.googlesource.com/q/I754b73a491ded468349b21ec4342b23c8ba9f87c

**Comment by andybons** [comment]
Andrew Bonventre has posted review comments on [go-review.googlesource.com](https://go-review.googlesource.com/c/scratch/+/87016#message-d1944009ec485210a0f038448c592641863fde18).

**Comment by andybons** [comment]
Andrew Bonventre has posted review comments on [go-review.googlesource.com](https://go-review.googlesource.com/c/scratch/+/87016#message-92ede1c0919d7456dc041e92237c578f87a0c3e5).

**Comment by andybons** [comment]
Andrew Bonventre has posted review comments on [go-review.googlesource.com](https://go-review.googlesource.com/c/scratch/+/87016#message-9871bccf6f2fd466c511f054b9d9fc5b8f984ef5).

**Comment by andybons** [comment]
Andrew Bonventre has posted review comments on [go-review.googlesource.com](https://go-review.googlesource.com/c/scratch/+/87016#message-310fa03c607faf8a233147ecbe8c8c92bf2e11a0).

**Comment by andybons** [comment]
Sam Saccone has posted review comments on [go-review.googlesource.com](https://go-review.googlesource.com/c/scratch/+/87016#message-643cf9080b120f7d6a736defe2b977c6a29e1383).

**Comment by andybons** [comment]
This PR is being closed because [golang.org/cl/87016](https://go-review.googlesource.com/c/scratch/+/87016) has been merged.

**Pull request closed without merging**
